### ISSUE TITLE
Can't downgrade from the latest patch

### ISSUE THREAD

**Issue by Gautam023** [cyanide-aoe2/wololo-downgrader#1]
Can't downgrade from the latest patch. 
![Screenshot (106)](https://user-images.githubusercontent.com/7250094/117064046-f756fb00-ad25-11eb-8168-05be3446f2f9.png)

**Comment by cyanide-aoe2** [comment]
I'll be updating the downgrader tomorrow for the latest update.

**Comment by cyanide-aoe2** [comment]
https://github.com/cyanide-aoe2/wololo-downgrader/releases/tag/v12

Updated.
